uasapp/urls.py
from django.urls import path
from .views import *

app_name="uasapp"
urlpatterns=[
path("",HomeView.as_view()),
path("register/",RegistrationView.as_view()),
path("login/",LoginView.as_view()),
path("logout/",LogoutView.as_view()),
path("protected/",ProtectedView.as_view()),
path("restricted/",RestrictedView.as_view()),
path("article/list/",ArticleListView.as_view()),
path("article/<int:pk>/detail/",ArticleDetailView.as_view()),
path("article/create/",ArticleCreateView.as_view()),
path("search/",SearchView.as_view(),name="search"),



]

uasproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("uasapp.urls"))
]
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

uasapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
	title=models.CharField(max_length=200)
	image=models.ImageField(upload_to="article")
	contents=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	author=models.ForeignKey(User,on_delete=models.CASCADE)
	view_count=models.PositiveIntegerField(default=0)
	#foreignkey:many articles by 1 user(db_relation)

	def __str__(self):
		return self.title
	#__str__ method for constructor


class Comment(models.Model):
	commentor=models.ForeignKey(User,on_delete=models.CASCADE)
	comment=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	article=models.ForeignKey(Article,on_delete=models.CASCADE)

	def __str__(self):
		return self.commentor.username

uasapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User 


class RegistrationForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	email=forms.CharField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())

	def clean_confirm_password(self):
		a=self.cleaned_data["password"]
		b=self.cleaned_data["confirm_password"]

		if a!=b:
			raise forms.ValidationError("password didn't match")
		return b

	def clean_username(self):
		a=self.cleaned_data["username"]
		if User.objects.filter(username=a).exists():
			raise forms.ValidationError("User with this username already exists.please choose different username.")

		return a



class LoginForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	password=forms.CharField(widget=forms.PasswordInput())

class ArticleForm(forms.ModelForm):
	class Meta:
		model=Article
		fields=["title","image","contents"]
		

uasapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import *
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q




class HomeView(TemplateView):
	template_name="home.html"

class RegistrationView(FormView):
	template_name="registration.html"
	form_class=RegistrationForm
	success_url="/"

	def form_valid(self,form):
		a=form.cleaned_data["username"]
		b=form.cleaned_data["email"]
		c=form.cleaned_data["password"]
		User.objects.create_user(a,b,c)


		return super().form_valid(form)

class LoginView(FormView):
	template_name="login.html"
	form_class=LoginForm
	success_url="/"

	def form_valid(self,form):
		a=form.cleaned_data["username"]
		b=form.cleaned_data["password"]
		user=authenticate(username=a,password=b)
		if user is not None:
			login(self.request,user)
		else: 
			return render(self.request,"login.html",{"error":"INVALID USERNAME OR PASSWORD","form":form})
		return super().form_valid(form)


class LogoutView(View):
	def get(self,request):
		logout(request)
		return redirect("/")

class ProtectedView(LoginRequiredMixin,TemplateView):  
	#LoginRequiredMixin:This View requires login 
	template_name="protected.html"
	login_url="/login/"

class RestrictedView(TemplateView):
	template_name="restricted.html"

	def dispatch(self,request,*args,**kwargs):
		usr=request.user
		if usr.is_authenticated and usr.username=="dipak":
			pass
		else:
			return redirect("/login/")


		return super().dispatch(request,*args,**kwargs)

class ArticleListView(ListView):
	template_name="articlelist.html"
	queryset=Article.objects.all().order_by("-id")
	context_object_name="allarticles"

class ArticleDetailView(DetailView):
	template_name="articledetail.html"
	model=Article
	context_object_name="articleobject"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		article_id=self.kwargs["pk"]
		article_object=Article.objects.get(id=article_id)
		# article_object=self.object (means line 82&83)
		article_object.view_count+=1
		article_object.save()

		return context



class ArticleCreateView(CreateView):
	template_name="addnewarticle.html"
	form_class=ArticleForm
	success_url="/article/list/"

	def dispatch(self,request,*args,**kwargs):
		usr=request.user
		if usr.is_authenticated:
			pass
		else:
			return redirect("/login/")


		return super().dispatch(request,*args,**kwargs)


	def form_valid(self,form):
		logged_in_user=self.request.user
		form.instance.author=logged_in_user
		return super().form_valid(form)

class SearchView(TemplateView):
	template_name="search.html"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		query=self.request.GET["keyword"]
		results=Article.objects.filter(Q(title__icontains=query)
			|Q(contents__icontains=query)|Q(author__username__icontains=query))
		context["search_results"]=results



		return context

class ArticleDetailView(DetailView):
	template_name="articledetail.html"
	model=Article
	context_object_name="articleobject"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		article_id=self.kwargs["pk"]
		article_object=Article.objects.get(id=article_id)
		# article_object=self.object (means line 82&83)
		article_object.view_count+=1
		article_object.save()

		return context

templates/addnewarticle.html
{% extends "base.html" %}

{% block body %}
<h3>Create New Article</h3>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Create Now</button>

</form>
{% endblock %}

templates/articledetail.html
{% extends "base.html" %}


{% block body %}

<h4>title:{{articleobject.title}}(viewed {{articleobject.view_count}} times) </h4>
{% if articleobject.image %}
<img src="{{articleobject.image.url}}" width="800">
{% endif %}
<p>contents:{{articleobject.contents}}</p>
<p>published date:{{articleobject.date}}</p>
<p>author:{{articleobject.author}}</p>
<!-- <div class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
 -->
 <h4>comments on this Post</h4>
 {% for comnt in articleobject.comment_set.all|dictsortreversed:"id" %}
 <li>{{comnt.commentor}} says {{comnt.comment}} {{comnt.date|timesince}} ago </li>

 {% endfor %}

{% endblock %}

templates/articlelist.html
{% extends "base.html" %}

{% block body %}


<table class="table table-bordered table-striped">

	<thead>
		<tr>
			<th>SN</th>
			<th>Title</th>
			<th>Date</th>
			<th>Author</th>
			<th>Image</th>
			<th>Content</th>
		</tr>
	</thead>
	<tbody>
		{% for article in allarticles %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="/article/{{article.id}}/detail/">{{article.title}}</a></td>
			<td>{{article.date}}</td>
			<th>{{article.author}}</th>
			<td><img src="{{article.image.url}}" width="100"></td>
			<td>{{article.contents|truncatewords:"10"}}</td>
		</tr>
		
		{% endfor %}
	</tbody>
</table>





{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<title></title>
</head>
<body>
	<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3"></script>

	<a href="/">Go to Home</a>
	<a href="/article/list/">Articles list</a>
	<a href="/article/create/">Create New Article</a>


	
{% if request.user.is_authenticated %}

Logged in as:<span style="color:blue">{{request.user}}</span>	
	<a href="/logout">Logout</a>
{% else %}
	<a href="/register">Registration</a>
	<a href="/login">Login</a>

{% endif %}

<form method="GET" action="{% url 'uasapp:search' %}">
	<input type="text" name="keyword" placeholder="search here.." value="{{request.GET.keyword}}">
	<button>Search</button>


</form>
<!-- Search Form -->





{% block body %}

{% endblock %}


</body>
</html>

templates/home.html
{% extends "base.html" %}


{% block body %}
<p style="background-color:cyan">Lyrics
G
Bebe I got ya
Friends come and go, friends come and go
Go like the seasons
I never know, I never know what to believe in
And it's getting old, it's getting old
But no hard feelings
'Cause friends come and go, friends come and go without a reason
And I, I've been in L.A. for way too long
Can't get this air inside my lungs
It feels like I'm suffocatin' from all the lack of the realness here
Is there anybody real out here?
Got my middle, middle up while I'm singing
Fuck fake friends, we don't need 'em
Only thing they're good for is leaving
Fuck fake friends, we don't need 'em
I've had it up to the ceiling
Fuck fake friends, we don't need 'em
Only thing they're good for is leaving
And I ain't got the time, money on my mind
I'll say it to your face, fuck fake friends
And lately I've been dealin' with mad stress
Comes with the territory of a Hollywood address
Is anybody real here? I need some fact checks
I need more realness, need you to act less
'Cause they deserve Oscars, so many imposters
What's up with guest lists?
Can I come to your concerts?
We all got demons, I'm dealin' with monsters
I've taken every picture, signed titties and signed shirts
But at the same time I know I'm blessed to be here
So let's just be clear, how many kids wish they had this spot
I got success, it's not a sandy beach chair
Be careful with the people you meet here, I'm sayin'
Uh, yeah
Is there anybody real out here? (G)
Got my middle, middle up while I'm singing (Uh)
Fuck fake friends, we don't need 'em
Only thing they're good for is leaving
Fuck fake friends, we don't need 'em
I've had it up to the ceiling
Fuck fake friends, we don't need 'em
Only thing they're good for is leaving
And I ain't got the time, money on my mind
I'll say it to your face, fuck fake friends
(Yeah) 
We don't need 'em
(Bebe, you know I feel you)
And I ain't got the time, money on my mind
Say it to my face, don't pretend
And I ain't got the time, money on my mind
I'll say it to your face, fuck fake friends
And I ain't got the time, money on my mind
Say it to my face, don't pretend
And I ain't got the time, money on my mind
I'll say it to your face, fuck fake friends
Is there anybody real out here?
Got my middle, middle up while I'm singing
Fuck fake friends, we don't need 'em
Only thing they're good for is leaving
Fuck fake friends, we don't need 'em
I've had it up to the ceiling
Fuck fake friends, we don't need 'em
Only thing they're good for is leaving
And I ain't got the time, money on my mind
I'll say it to your face, fuck fake friends</p>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block body %}
<h3>Login Form</h3>
<p>{{error}}</p>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Login</button>

</form>
If you don't have account yet, <a href="/register/">Register</a>
{% endblock %}

templates/registration.html
{% extends "base.html" %}

{% block body %}
<h3>Registration Form</h3>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Register</button>
</form>
{% endblock %}

templates/search.html
{% extends "base.html" %}



{% block body %}
<h3>Search Results for <span class="text-info">{{request.GET.keyword}}</span></h3>
{% for article in search_results %}

<li>{{article.title}}</li>
<img src="{{article.image.url}}" width="200">
<p><a href="/article/{{article.id}}/detail/">details</a></p>
{% empty %}
<p>No Results Found</p>

{% endfor %}


{% endblock %}